apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/konflux-ci/container-build-catalog?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "false"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch
      == "main" && ( "task/build-image-index-min/***".pathChanged() || ".tekton/task-build-image-index-min-push.yaml".pathChanged()
      || "Containerfile".pathChanged() )
  labels:
    appstudio.openshift.io/application: konflux-container-build-catalog
    appstudio.openshift.io/component: task-build-image-index-min
    pipelines.appstudio.openshift.io/type: build
  name: task-build-image-index-min-on-push
  namespace: rhtap-build-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/rhtap-build-tenant/konflux-container-build-catalog/build-image-index-min:{{revision}}
  - name: dockerfile
    value: Containerfile
  - name: path-context
    value: task/build-image-index-min
  pipelineRef:
    name: build-tekton-bundle
  taskRunTemplate:
    serviceAccountName: build-pipeline-task-build-image-index-min
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
